### ISSUE TITLE
Add server status badge to free-storage README

### ISSUE THREAD

**Issue by joekroese** [grammyjs/storages#134]
The freeStorage seems to be down, giving a 503 error: `503 in free session service, retrying!`.

It would be good for users to know if the server is down. An easy way to do this, depending on the deployment, would be adding a server status badge to the README file.

**Comment by KnorpelSenf** [comment]
Can you elaborate how you think one can test this?

**Comment by joekroese** [comment]
To build it from scratch, I guess make a regular request to the server and if you get an error, report that.

But I was thinking more about using something prebuilt. Some deployment options have these badges available to just copy (e.g. Netlify). If Deno Deploy doesn't offer something similar, I had a quick search and [Pulsetic](https://pulsetic.com/) could be an option.

**Comment by KnorpelSenf** [comment]
It sounds to me like all we can do is to build a second system (which might fail in the same way) just to report the status of the first system. If we run this system on the same infra, we gain nothing, and if we run it on a different infra, we just duplicate the risk. Either way, it adds complexity but I still don't understand how it helps.

The current downtime is caused because Deno suspended the deployment without any notice whatsoever (despite promising transparency on their website). I've asked @lucacasonato today via email why this happened, but received no reply so far.

**Comment by joekroese** [comment]
Sure! I've found badges useful in other projects for letting users know what's happening with a server. But if it's not easy within Deno or using a third-party option then it makes sense to leave it.

> Deno suspended the deployment without any notice whatsoever

Very strange! Hope it comes back soon.

**Comment by KnorpelSenf** [comment]
Unless Deno suspends the project, you can use https://denostatus.com to check :)
